allowBuilds:
  '@swc/core': false
  esbuild: set this to true or false
  unrs-resolver: false


blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

overrides:
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

strictPeerDependencies: false

trustPolicy: no-downgrade
