allowBuilds:
  '@swc/core': false
  esbuild: set this to true or false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - brace-expansion@5.0.8 || 5.0.9

overrides:
  brace-expansion@<=5.0.7: ^5.0.8
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

strictPeerDependencies: false

trustPolicy: no-downgrade
