name: Build and Test
 
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 'lts/*'
        check-latest: true
        package-manager-cache: false

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: false
            cwd: .
            args: [--no-frozen-lockfile]

    - name: Build and Unittest
      run: pnpm all
  